### PR TITLE
Added array flattening for input folders

### PR DESCRIPTION
**Pull request by meszaros-lajos-gyorgy**
Added solution to the [issue that I opened](https://github.com/bahmutov/rollem/issues/24)

### CODE REVIEW

**Comment by snuggs** [comment]
@meszaros-lajos-gyorgy thanks for catching this! Let me know what I can do to help get this merged in ASAP.

**Comment by bahmutov** [comment]
@meszaros-lajos-gyorgy Could you add unit test for this function, please? Just to make sure we will not break it in the future. It became a little "hairy" due to extra fold. But in general, why not use http://ramdajs.com/docs/#flatten to do this?

**Comment by meszaros-lajos-gyorgy** [comment]
@bahmutov Thanks for the tip on ramdajs's flatten. Didn't know it has this function. Of course, the code can be changed, so that it will use this.
Also I would like to extend this fix by introducing glob for url patterns to address issue #26.

**Comment by meszaros-lajos-gyorgy** [comment]
Glob watch added, this should fix #26.

**Comment by meszaros-lajos-gyorgy** [comment]
Guys? Any feedback on this? When can this be merged?

**Comment by meszaros-lajos-gyorgy** [comment]
Found an issue with my fix, gonna post fix soon.

**Comment by meszaros-lajos-gyorgy** [comment]
watch-glob needed an extra /** at the end of the folders, because without that it only watched the folder, not it's contents. Added unit tests and fix. Added this as another case in the test build.

**Pull request merged**
