### PR TITLE
Add deprecation notice

### LINKED ISSUE #44: This is now part of rollup core
Rollup 0.42+ as per https://github.com/rollup/rollup/pull/1389

### PR DESCRIPTION
**Pull request by fregante**
Closes #44

### CODE REVIEW

**Comment by snuggs** [comment]
@bahmutov thoughts?

**Comment by ghost** [comment]
@snuggs please see my comment in #44 

`rollem` still provides value to API consumers, even if `rollup` CLI has multiple config support. If we could get `rollup` to expose their [execute](https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L133) function, then I think all current use cases for `rollem` would be met.

**Comment by snuggs** [comment]
Great work on info wrangling @destroyerofbuilds @bfred-it. Going by reading all docs / PRs / Issues I'd say a `deprecated` warning may be a little preemptive perhaps? But definitely hadn't had it on my radar.

Please advise...

#salute 🙏 

/cc @bahmutov

**Comment by bahmutov** [comment]
Thanks for closing the loop everyone, `rollem` was really a user-space iterator on top of `rollup` so it is great to see this feature added to the core. Sorry for taking so long to merge this, work, travel and family :)

**Pull request merged**
